// <auto-generated />
using System;
using GorevYonetimSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GorevYonetimSistemi.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("GorevYonetimSistemi.Data.Entities.Duty", b =>
                {
                    b.Property<Guid>("DutyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("DutyId");

                    b.ToTable("Duties", (string)null);
                });

            modelBuilder.Entity("GorevYonetimSistemi.Data.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GorevYonetimSistemi.Data.Entities.UserDuty", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DutyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserDutyId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "DutyId");

                    b.HasIndex("DutyId");

                    b.ToTable("UserDuties", (string)null);
                });

            modelBuilder.Entity("GorevYonetimSistemi.Data.Entities.UserDuty", b =>
                {
                    b.HasOne("GorevYonetimSistemi.Data.Entities.Duty", "Duty")
                        .WithMany("UserDuties")
                        .HasForeignKey("DutyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GorevYonetimSistemi.Data.Entities.User", "User")
                        .WithMany("UserDuties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Duty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GorevYonetimSistemi.Data.Entities.Duty", b =>
                {
                    b.Navigation("UserDuties");
                });

            modelBuilder.Entity("GorevYonetimSistemi.Data.Entities.User", b =>
                {
                    b.Navigation("UserDuties");
                });
#pragma warning restore 612, 618
        }
    }
}
